modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "demagnetizer"
version = "${version}"
displayName = "Demagnetizer"
authors = "aruloci"
description = '''
An item that disables Sophisticated Storage magnet upgrades inside a configurable cube. Requires Sophisticated Core.
'''

[[dependencies.demagnetizer]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.demagnetizer]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.demagnetizer]]
modId = "sophisticatedcore"
type = "required"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.demagnetizer]]
modId = "sophisticatedbackpacks"
type = "optional"
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "demagnetizer.mixins.json"
